version: '2'
services:
  elasticsearch:
    image: elasticsearch:2
    command: elasticsearch -Des.network.bind_host=0.0.0.0
    ports:
      - "9200:9200"
      - "9300:9300"

  skydive-analyzer:
    image: skydive/skydive
    ports:
      - "2379:2379"
      - "8082:8082"
      - "8082:8082/udp"
    links:
      - elasticsearch
    command: analyzer --listen=0.0.0.0:8082
    environment:
      - SKYDIVE_STORAGE_ELASTICSEARCH_HOST=elasticsearch:9200
      - SKYDIVE_ANALYZER_STORAGE=elasticsearch
      - SKYDIVE_GRAPH_BACKEND=elasticsearch

  skydive-agent:
    image: skydive/skydive
    depends_on:
      - skydive-analyzer
    ports:
      - "8081:8081"
    network_mode: "host"
    pid: "host"
    command: agent --listen=0.0.0.0:8081
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/run/netns:/host/run:shared
      - /var/run/openvswitch:/var/run/openvswitch
    environment:
      - SKYDIVE_NETNS_RUN_PATH=/host/run
      - SKYDIVE_ANALYZERS=127.0.0.1:8082
