version: '2'

services:
  openstack:
    build: .
    ports:
      - "8000:80"
      - "4443:443"
      - "6640:6640"
    cap_add: 
      - SYS_ADMIN
      - SYS_MODULE
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /var/run/dbus:/var/run/dbus
      - /var/systemd:/var/systemd
      - /var/run/openvswitch:/var/run/openvswitch
    tmpfs:
      - /run
      - /run/lock
    environment:
      - "container=docker"
    privileged: true
  rabbitmq:
    image: rabbitmq:latest
    environment:
      - RABBITMQ_DEFAULT_PASS=st4ckb0ss
      - RABBITMQ_DEFAULT_USER=stackrabbit
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=st4ckb0ss
